version: 0.2
phases:
  pre_build:
    commands:
      - echo Mencoba login ke AWS ECR...
      - aws --version
      - AWS_DEFAULT_REGION=ap-southeast-1
      - AWS_ACCOUNT_ID=623127157773
      - REPOSITORY_NAME=herley-springboot-test
      - REPOSITORY_TAG=latest
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - mvn clean install
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$REPOSITORY_NAME:$REPOSITORY_TAG
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo Build dimulai pada `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_NAME .
  post_build:
    commands:
      - echo Build selesai `date`
      - echo Pushing the Docker images...
      - docker tag $REPOSITORY_NAME:$REPOSITORY_TAG $REPOSITORY_URI
      - docker push $REPOSITORY_URI
#      - docker tag herley-springboot-test:latest 623127157773.dkr.ecr.ap-southeast-1.amazonaws.com/herley-springboot-test:latest
#      - docker push 623127157773.dkr.ecr.ap-southeast-1.amazonaws.com/herley-springboot-test:latest
      - echo Writing image definitions file...
      - printf '[{"name":"hello-container","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imageexplanations.json
      - cat imageexplanations.json
artifacts:
  files:
    - imageexplanations.json
    - target/SimpleHello-0.0.1-SNAPSHOT.jar