version: 0.2
phases:
  pre_build:
    commands:
      - echo Mencoba login ke AWS ECR...
      - aws --version
      - AWS_DEFAULT_REGION=<REGION-ANDA>
      - AWS_ACCOUNT_ID=<AWS-ACCOUNT-ID-ANDA>
      - REPOSITORY_NAME=<NAMA-REPOSITORI-ECR-ANDA>
      - REPOSITORY_TAG=latest
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
#      - mvn clean install
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$REPOSITORY_NAME:$REPOSITORY_TAG
      - REPOSITORY_URI_UNTAG=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$REPOSITORY_NAME
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
      - LATEST_IMAGE_TAG=latest
  build:
    commands:
      - echo Build dimulai pada `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_NAME .
  post_build:
    commands:
      - echo Build selesai `date`
      - echo Pushing the Docker images...
      - docker tag $REPOSITORY_NAME:$REPOSITORY_TAG $REPOSITORY_URI
      - docker push $REPOSITORY_URI
      - echo Writing image definitions file...
      - printf '[{"name":"hello-world-container","imageUri":"%s"}]' $REPOSITORY_URI_UNTAG:$LATEST_IMAGE_TAG > imageexplanations.json
      - cat imageexplanations.json
artifacts:
  files:
    - imageexplanations.json
    - target/SimpleHello-0.0.1-SNAPSHOT.jar